### ISSUE TITLE
As a user I can send code file via front-end

### ISSUE THREAD

**Issue by TheJiahao** [game-ai-platform-team/tira-ai-platform#1]
## Tasks

- [x] File submit component
- [x] File submit handler
- [x] Submitted content component
- [x] Backend route `/api/submit` for sending file
- [x] Testing
- [x] Documentation
