### ISSUE TITLE
Refactor backend to match architecture document

### ISSUE THREAD

**Issue by TheJiahao** [game-ai-platform-team/tira-ai-platform#17]
## Tasks
- [x] Add Api class
- [x] Split Chess class
- [x] Add Player class
- [x] Add ChessJudger class
- [x] Move functionalities to ChessJudger class
- [x] Documentation
- [x] Return game result in JSON
- [x] Launch Chess game in Api class
