### ISSUE TITLE
Replace stockfish code with Python package

### ISSUE THREAD

**Issue by TheJiahao** [game-ai-platform-team/tira-ai-platform#18]
## Tasks
- [ ] Add [stockfish](https://pypi.org/project/stockfish/) package
- [ ] Remove stockfish code from Git using `filter-branch` and force push changes
- [ ] Inform all developers to force pull to local repository
