### ISSUE TITLE
Remove Python binaries from Git repository history

### ISSUE THREAD

**Issue by TheJiahao** [game-ai-platform-team/tira-ai-platform#19]
## Tasks
- [x] Delete Python binary
- [x] Remove Python binary from Git log permanently using `git-filter-repo` and force push changes
- [x] Inform all developers to force pull to local repository
