### ISSUE TITLE
Add end-to-end/acceptance tests using Cypress

### ISSUE THREAD

**Issue by TheJiahao** [game-ai-platform-team/tira-ai-platform#20]
## Tasks
- [x] Configure Cypress
- [x] Configure GitHub Actions and cypress
- [x] Add tests
  - [x] Submitting files through frontend succeeds
  - [x] Game starts after sending file
