### ISSUE TITLE
As a user I can see statistics of a move

### ISSUE THREAD

**Issue by MiikaMatias** [game-ai-platform-team/tira-ai-platform#25]
## Tasks
- [x] Add `Move` class representing a single move
    ```ts
    {
        move: string
        time: int
        state: string
    }
    ```
- [x] Return time of a single move via socket
- [x] Show time of a single move in frontend
- [x] Test Move component
