### ISSUE TITLE
Refactor Game, ChessGame and GameFactory

### ISSUE THREAD

**Issue by TheJiahao** [game-ai-platform-team/tira-ai-platform#48]
## Tasks

- [x] Move game logic to Game
- [x] Only initialize Game objects with GameFactory
- [x] `validate` and `add_move` explicitly
- [x] `play_one_move`, `validate` and send moves excplicitly
- [x] Remove ChessGame class
- [x] Add tests
- [x] Add `Move` class to represent a move
- [x] Make methods not in architecture private
