### ISSUE TITLE
Add more unit tests and coverage report

### ISSUE THREAD

**Issue by TheJiahao** [game-ai-platform-team/tira-ai-platform#49]
## Tasks

- [ ] Game class
- [ ] Judge class
- [ ] GameFactory class
- [ ] SocketIOService class
- [ ] Player class
- [ ] Generate coverage report for backend
- [ ] Generate coverage report for frontend
- [ ] Upload aggregated coverage report to somewhere
- [ ] Add coverage badge to README.md
