### ISSUE TITLE
Sort components in frontend according to architecture

### ISSUE THREAD

**Issue by TheJiahao** [game-ai-platform-team/tira-ai-platform#73]
## Tasks
- [x] Rename components according to architecture
- [x] Refactor `AdvantageBar` to use svg
- [x] Refactor `GameView`
  - [x] Make `MoveList` independent of parent
  - [x] Replace redundant div-containers with classNames in React components
  - [x] Pass board as a parameter
- [x] Fix layout without changing styles of child elements directly
  - [x] Remove all margins in top level element of a component, except `GameView`
  - [x] Tweak `gap` and `align-items` of `game-view`
- [x] Move components according to architecture
- [x] Rename `GameConnection` to `SocketService`
- [x] Encapsulate all socket-related things into SocketService
- [x] Call `SocketService.startGame` when user submits file
- [x] Test `ChessBoard`
- [x] Test `GameView`, check everything gets rendered
- [x] Fix test of Move
