### ISSUE TITLE
Add coverage report

### ISSUE THREAD

**Issue by TheJiahao** [game-ai-platform-team/tira-ai-platform#90]
## Tasks
- [x] Upload aggregated coverage report to somewhere, codecov?
- [x] Upload backend and frontend coverage at once
- [x] Add coverage badge to README.md
